name: Bug
description: Something in the repo (docs/templates) is incorrect or broken.
title: "Bug: <short summary>"
labels: ["bug"]
body:
  - type: textarea
    id: bug
    attributes:
      label: What happened?
      description: Describe the bug and where it occurs (file/path/section).
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
